environment:
  nodejs_version: "5.5.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - ant compile

test_script:
  - node --version
  - npm --version
  - npm test

build: off
